using System.Text.RegularExpressions;
using OpenQA.Selenium;
using OpenQA.Selenium.Appium;
using System.Threading;
using System;
using TestProject.SDK;
using TestProject.SDK.Tests.Helpers;
using TestProject.SDK.Tests;
using TestProject.Common.Attributes;
using TestProject.Common.Enums;

namespace TestProject.Generated.Tests.MyFirstProject
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Project: My first Project
	/// Test: CP006-F
	/// Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
	/// Generated on: 10/13/2021 01:10:28
	/// </summary>
	public class CP006F : IWebTest
	{
		[ParameterAttribute(Description = "Auto generated application URL parameter", DefaultValue = "http://localhost/ActiveTime/", Direction = ParameterDirection.Input)]
		public string ApplicationURL;
		[ParameterAttribute(Direction = ParameterDirection.Input)]
		public string usuario;
		[ParameterAttribute(Direction = ParameterDirection.Input)]
		public string Idtarea;
		public ExecutionResult Execute(WebTestHelper helper)
		{
			var driver = helper.Driver;
			var report = helper.Reporter;
			bool boolResult;
			By by;
			ExecutionResult executionResult;
			io.testproject.addons.web.alert.AcceptAlert acceptAlert;
			
			// set timeout for driver actions (similar to step timeout)
			driver.Timeout = 15000;
			
			 // 1. Navigate to '{{ApplicationURL}}'
			// Navigates the specified URL (Auto-generated)
			// Add step sleep time (Before)
			Thread.Sleep(500);
			boolResult = driver.TestProject().NavigateToURL(ApplicationURL);
			report.Step(string.Format("Navigate to '{0}'", ApplicationURL), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 2. Click 'user'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#user");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'user'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 3. Type 'jdme1' in 'user'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#user");
			boolResult = driver.TestProject().TypeText(by, "jdme1");
			report.Step("Type 'jdme1' in 'user'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 4. Click 'password'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#password");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'password'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 5. Type 'lindo123!' in 'password'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#password");
			boolResult = driver.TestProject().TypeText(by, "lindo123!");
			report.Step("Type 'lindo123!' in 'password'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 6. Click 'Log in'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#ingresar");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Log in'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 7. Scroll window by ('0','559')
			// Add step sleep time (Before)
			Thread.Sleep(500);
			boolResult = driver.TestProject().ScrollWindow(0, 559);
			report.Step("Scroll window by ('0','559')", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 8. Click 'Share Task'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#shareTask");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Share Task'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 9. Scroll window by ('0','56')
			// Add step sleep time (Before)
			Thread.Sleep(500);
			boolResult = driver.TestProject().ScrollWindow(0, 56);
			report.Step("Scroll window by ('0','56')", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 10. Click 'Compartir'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#share");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Compartir'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 11. Accept alert
			// Add step sleep time (Before)
			Thread.Sleep(500);
			acceptAlert = TestProject.Addons.Proxy.WebExtensions.CreateAcceptAlert(0);
			executionResult = helper.ExecuteProxy(acceptAlert);
			report.Step("Accept alert", executionResult == ExecutionResult.Passed, TakeScreenshotConditionType.Failure);
			
			 // 12. Accept alert
			// Add step sleep time (Before)
			Thread.Sleep(500);
			acceptAlert = TestProject.Addons.Proxy.WebExtensions.CreateAcceptAlert(0);
			executionResult = helper.ExecuteProxy(acceptAlert);
			report.Step("Accept alert", executionResult == ExecutionResult.Passed, TakeScreenshotConditionType.Failure);
			
			 // 13. Click 'IDtask'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#IDtask");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'IDtask'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 14. Type '{{Idtarea}}' in 'IDtask'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#IDtask");
			boolResult = driver.TestProject().TypeText(by, Idtarea);
			report.Step(string.Format("Type '{0}' in 'IDtask'", Idtarea), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 15. Click 'user'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#user");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'user'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 16. Type '{{usuario}}' in 'user'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#user");
			boolResult = driver.TestProject().TypeText(by, usuario);
			report.Step(string.Format("Type '{0}' in 'user'", usuario), boolResult, TakeScreenshotConditionType.Failure);
			
			 // 17. Click 'Compartir'
			// Add step sleep time (Before)
			Thread.Sleep(500);
			by = By.CssSelector("#share");
			boolResult = driver.TestProject().Click(by);
			report.Step("Click 'Compartir'", boolResult, TakeScreenshotConditionType.Failure);
			
			 // 18. Accept alert
			// Add step sleep time (Before)
			Thread.Sleep(500);
			acceptAlert = TestProject.Addons.Proxy.WebExtensions.CreateAcceptAlert(0);
			executionResult = helper.ExecuteProxy(acceptAlert);
			report.Step("Accept alert", executionResult == ExecutionResult.Passed, TakeScreenshotConditionType.Failure);
			
			return ExecutionResult.Passed;
		}
	}
}