using TestProject.Common.DTO.ExecutionResult;
using TestProject.Common.Enums;
using System;
using System.Reflection;
using TestProject.SDK;

namespace TestProject.Generated.Tests.MyFirstProject
{
	/// <summary>
	/// This class was automatically generated by TestProject
	/// Provides an example how to run coded TestProject tests
	/// </summary>
	public class MyFirstProjectRunner
	{
		public static string DevToken = "Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0";
		public static AutomatedBrowserType Browser = AutomatedBrowserType.Chrome;
		public static StepExecutionResult RunCP006F()
		{
			using (var runner = new RunnerBuilder(DevToken).AsWeb(Browser).Build())
				return runner.Run(new CP006F(), true);
		}

		public static void Main(string[] args)
		{
			try
			{
				Assembly.LoadFrom("Addons/Web-Extensions.proxy.dll");
				RunCP006F();
			}
			catch (Exception ex)
			{
				Console.WriteLine(ex);
			}
		}
	}
}