from addons.web_extensions import WebExtensions
from selenium.webdriver.common.by import By
from src.testproject.classes import DriverStepSettings, StepSettings
from src.testproject.decorator import report_assertion_errors
from src.testproject.enums import SleepTimingType
from src.testproject.sdk.drivers import webdriver
import pytest


"""
This pytest test was automatically generated by TestProject
    Project: My first Project
    Package: TestProject.Generated.Tests.MyFirstProject
    Test: CP006-F
    Generated by: Channyke Rodriguez (csrodriguez21@ucatolica.edu.co)
    Generated on 10/13/2021, 01:10:51
"""


@pytest.fixture()
def driver():
    driver = webdriver.Chrome(token="Dl_CRrVGkr6XQ2tp-Eg4dJ3yWlOTRQ7XPZwrxjLFM_0",
                              project_name="My first Project",
                              job_name="CP006-F")
    step_settings = StepSettings(timeout=15000,
                                 sleep_time=500,
                                 sleep_timing_type=SleepTimingType.Before)
    with DriverStepSettings(driver, step_settings):
        yield driver
    driver.quit()


@report_assertion_errors
def test_main(driver):
    """Caso de prueba 6 fallido."""
    # Test Parameters
    # Auto generated application URL parameter
    ApplicationURL = "http://localhost/ActiveTime/"
    usuario = ""
    Idtarea = ""

    # 1. Navigate to '{ApplicationURL}'
    # Navigates the specified URL (Auto-generated)
    driver.get(f'{ApplicationURL}')

    # 2. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 3. Type 'jdme1' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys("jdme1")

    # 4. Click 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.click()

    # 5. Type 'lindo123!' in 'password'
    password = driver.find_element(By.CSS_SELECTOR,
                                   "#password")
    password.send_keys("lindo123!")

    # 6. Click 'Log in'
    log_in = driver.find_element(By.CSS_SELECTOR,
                                 "#ingresar")
    log_in.click()

    # 7. Scroll window by ('0','559')
    driver.execute_script("window.scrollBy(0,559)")

    # 8. Click 'Share Task'
    share_task = driver.find_element(By.CSS_SELECTOR,
                                     "#shareTask")
    share_task.click()

    # 9. Scroll window by ('0','56')
    driver.execute_script("window.scrollBy(0,56)")

    # 10. Click 'Compartir'
    compartir = driver.find_element(By.CSS_SELECTOR,
                                    "#share")
    compartir.click()

    # 11. Accept alert
    driver.addons().execute(
        WebExtensions.acceptalert(
            pause=0))

    # 12. Accept alert
    driver.addons().execute(
        WebExtensions.acceptalert(
            pause=0))

    # 13. Click 'IDtask'
    idtask = driver.find_element(By.CSS_SELECTOR,
                                 "#IDtask")
    idtask.click()

    # 14. Type '{Idtarea}' in 'IDtask'
    idtask = driver.find_element(By.CSS_SELECTOR,
                                 "#IDtask")
    idtask.send_keys(f'{Idtarea}')

    # 15. Click 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.click()

    # 16. Type '{usuario}' in 'user'
    user = driver.find_element(By.CSS_SELECTOR,
                               "#user")
    user.send_keys(f'{usuario}')

    # 17. Click 'Compartir'
    compartir = driver.find_element(By.CSS_SELECTOR,
                                    "#share")
    compartir.click()

    # 18. Accept alert
    driver.addons().execute(
        WebExtensions.acceptalert(
            pause=0))
